apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off

    [INPUT]
        Name              tail
        Path              /var/log/containers/myapp-*_default_*.log
        Parser            docker
        Tag               myapp.*
        Refresh_Interval  5
    [OUTPUT]
        Name             s3
        Match            *
        bucket           s3-my-buck
        region           us-east-1
        total_file_size  1M
        upload_timeout   1m
        use_put_object   On
        s3_key_format    /myapp/${HOSTNAME}/%Y/%m/%d/%H/myapp.log
